import Header from "@/components/Header/Header";
import { NavbarHeightSpacingHelper } from "@/components/Header/Navbar";
import theme from "@/theme";
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <Box sx={{ display: "flex", height: "100%", width: "100%", position: "fixed" }}>
              <CssBaseline />
              <Header sidebarWidth={260} />
              <Box component="main" sx={{ flexGrow: 1, p: 3, backgroundColor: "grey.100" }}>
                <NavbarHeightSpacingHelper />
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
